version: "3"
services:
  web:
    image: cobreti/wsagtor:latest
    volumes:
      - "./server:/var/www/websites/server"
      - "./web:/var/www/websites/web"
    environment:
      NODE_ENV: "development"
    ports:
      - "${wsagtor_http}:8000"
      - "${wsagtor_https}:8001"
      - "9229:8002"
      - "5858:5858"
    working_dir: /var/www/websites/server/nodejs
    entrypoint: ["npm", "start"]

