version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    image: cobreti/wsagtor:latest
    ports:
      - "${wsagtor_http}:8000"
      - "${wsagtor_https}:8001"
